feat(api): added get-segments sdk endpoint
switchfeat-com/switchfeat pull request #37
Opened 2023-07-22 17:57 UTC by lazyfuhrer

2023-07-23 20:15 UTC, dev-bre requested changes
looks good overall, I have some minor comments it would great you could address.

2023-07-23 20:15 UTC, dev-bre commented on packages/api/src/routes/sdkRoutes.ts
> +            const flag = await flagsService.getRulesByFlag(flagKey);
this should be called: `rules`

2023-07-23 20:15 UTC, dev-bre commented on packages/api/src/services/flagsService.ts
> +        throw error;
please log the error here.

2023-07-23 20:15 UTC, dev-bre commented on packages/api/src/services/segmentsService.ts
> +        throw error;
please log the error

2023-07-23 20:15 UTC, dev-bre commented on packages/api/src/routes/sdkRoutes.ts
> +    sdkRoutes.get("/api/sdk/conditionsbysegment", auth.isAuthenticated, async (req: Request, res: Response) => {
to keep consitency you can call the url: `/segments/:segmentKey/conditions` and read the data from the `req.params`

2023-07-23 20:15 UTC, dev-bre commented on packages/api/src/services/flagsService.ts
> +import { RuleModel } from "@switchfeat/core/dist/models/ruleModel";
please import the models from /core and not from /dist

2023-07-23 20:15 UTC, dev-bre commented on packages/api/src/routes/sdkRoutes.ts
> +    sdkRoutes.get("/api/sdk/rulesbyflag", auth.isAuthenticated, async (req: Request, res: Response) => {
to keep consitency you can call the url:` /flags/:flagKey/rules` and read the data from the` req.params`

2023-07-24 12:29 UTC, lazyfuhrer commented
All done!

2023-07-24 12:57 UTC, merged

2023-07-24 12:57 UTC, dev-bre commented
@lazyfuhrer well done! thansk for your contribution!